"""initial_schema

Revision ID: 6dae9e7efe75
Revises: 
Create Date: 2026-03-31 18:27:34.695550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dae9e7efe75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=256), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tickers_json', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_events_event_id'), 'news_events', ['event_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=256), nullable=False),
    sa.Column('broker_order_id', sa.String(length=256), nullable=True),
    sa.Column('signal_id', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('close_after_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_close_after_date'), 'orders', ['close_after_date'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_signal_id'), 'orders', ['signal_id'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_table('stage1_positions',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('size_pct', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('expected_report_date', sa.Date(), nullable=False),
    sa.Column('fiscal_quarter', sa.String(length=32), nullable=False),
    sa.Column('historical_beat_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage1_positions_expected_report_date'), 'stage1_positions', ['expected_report_date'], unique=False)
    op.create_index(op.f('ix_stage1_positions_status'), 'stage1_positions', ['status'], unique=False)
    op.create_index(op.f('ix_stage1_positions_ticker'), 'stage1_positions', ['ticker'], unique=False)
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=256), nullable=False),
    sa.Column('event_id', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('conviction', sa.Float(), nullable=False),
    sa.Column('suggested_qty', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_signals_event_id'), 'trade_signals', ['event_id'], unique=False)
    op.create_index(op.f('ix_trade_signals_signal_id'), 'trade_signals', ['signal_id'], unique=True)
    op.create_index(op.f('ix_trade_signals_ticker'), 'trade_signals', ['ticker'], unique=False)
    op.create_table('watchlist_selections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tickers_json', sa.Text(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('stage1_id', sa.String(length=256), nullable=True),
    sa.Column('final_status', sa.String(length=16), nullable=False),
    sa.Column('eps_surprise_pct', sa.Float(), nullable=True),
    sa.Column('price_move_1d', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stage1_id'], ['stage1_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_outcomes_stage1_id'), 'earnings_outcomes', ['stage1_id'], unique=True)
    op.create_index(op.f('ix_earnings_outcomes_ticker'), 'earnings_outcomes', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_outcomes_ticker'), table_name='earnings_outcomes')
    op.drop_index(op.f('ix_earnings_outcomes_stage1_id'), table_name='earnings_outcomes')
    op.drop_table('earnings_outcomes')
    op.drop_table('watchlist_selections')
    op.drop_index(op.f('ix_trade_signals_ticker'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_signal_id'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_event_id'), table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index(op.f('ix_stage1_positions_ticker'), table_name='stage1_positions')
    op.drop_index(op.f('ix_stage1_positions_status'), table_name='stage1_positions')
    op.drop_index(op.f('ix_stage1_positions_expected_report_date'), table_name='stage1_positions')
    op.drop_table('stage1_positions')
    op.drop_index(op.f('ix_orders_ticker'), table_name='orders')
    op.drop_index(op.f('ix_orders_signal_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_close_after_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_news_events_event_id'), table_name='news_events')
    op.drop_table('news_events')
    # ### end Alembic commands ###
