"""add_gov_trade_tables

Revision ID: a37c13cedc56
Revises: a1b2c3d4e5f6
Create Date: 2026-05-05 18:19:49.938439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37c13cedc56'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('award_id', sa.String(length=256), nullable=False),
    sa.Column('recipient_name', sa.Text(), nullable=False),
    sa.Column('recipient_uei', sa.String(length=64), nullable=True),
    sa.Column('recipient_parent_name', sa.Text(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('awarding_agency', sa.Text(), nullable=False),
    sa.Column('awarding_sub_agency', sa.Text(), nullable=True),
    sa.Column('award_type', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('naics_code', sa.String(length=16), nullable=True),
    sa.Column('naics_description', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('sign_date', sa.Date(), nullable=False),
    sa.Column('last_modified_date', sa.Date(), nullable=True),
    sa.Column('place_of_performance_state', sa.String(length=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_awards_award_id'), 'contract_awards', ['award_id'], unique=True)
    op.create_index(op.f('ix_contract_awards_sign_date'), 'contract_awards', ['sign_date'], unique=False)
    op.create_table('enrichment_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_award_id', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('agency', sa.Text(), nullable=False),
    sa.Column('multiplier_applied', sa.Float(), nullable=False),
    sa.Column('data_found', sa.Integer(), nullable=False),
    sa.Column('spend_delta_pct', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_log_contract_award_id'), 'enrichment_log', ['contract_award_id'], unique=False)
    op.create_index(op.f('ix_enrichment_log_ticker'), 'enrichment_log', ['ticker'], unique=False)
    op.create_table('entity_resolutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('award_id', sa.String(length=256), nullable=False),
    sa.Column('recipient_name', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_resolutions_award_id'), 'entity_resolutions', ['award_id'], unique=False)
    op.create_index(op.f('ix_entity_resolutions_ticker'), 'entity_resolutions', ['ticker'], unique=False)
    op.create_table('gov_trade_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=256), nullable=False),
    sa.Column('award_id', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('conviction', sa.Float(), nullable=False),
    sa.Column('suggested_qty', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('materiality_score', sa.Float(), nullable=True),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gov_trade_signals_award_id'), 'gov_trade_signals', ['award_id'], unique=False)
    op.create_index(op.f('ix_gov_trade_signals_signal_id'), 'gov_trade_signals', ['signal_id'], unique=True)
    op.create_index(op.f('ix_gov_trade_signals_ticker'), 'gov_trade_signals', ['ticker'], unique=False)
    op.create_table('lobbying_filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('lda_client_name', sa.Text(), nullable=False),
    sa.Column('filing_uuid', sa.String(length=256), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('total_spend', sa.Float(), nullable=False),
    sa.Column('agency_breakdown_json', sa.Text(), nullable=False),
    sa.Column('lobbied_agencies_json', sa.Text(), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobbying_filings_filing_uuid'), 'lobbying_filings', ['filing_uuid'], unique=True)
    op.create_index(op.f('ix_lobbying_filings_ticker'), 'lobbying_filings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lobbying_filings_ticker'), table_name='lobbying_filings')
    op.drop_index(op.f('ix_lobbying_filings_filing_uuid'), table_name='lobbying_filings')
    op.drop_table('lobbying_filings')
    op.drop_index(op.f('ix_gov_trade_signals_ticker'), table_name='gov_trade_signals')
    op.drop_index(op.f('ix_gov_trade_signals_signal_id'), table_name='gov_trade_signals')
    op.drop_index(op.f('ix_gov_trade_signals_award_id'), table_name='gov_trade_signals')
    op.drop_table('gov_trade_signals')
    op.drop_index(op.f('ix_entity_resolutions_ticker'), table_name='entity_resolutions')
    op.drop_index(op.f('ix_entity_resolutions_award_id'), table_name='entity_resolutions')
    op.drop_table('entity_resolutions')
    op.drop_index(op.f('ix_enrichment_log_ticker'), table_name='enrichment_log')
    op.drop_index(op.f('ix_enrichment_log_contract_award_id'), table_name='enrichment_log')
    op.drop_table('enrichment_log')
    op.drop_index(op.f('ix_contract_awards_sign_date'), table_name='contract_awards')
    op.drop_index(op.f('ix_contract_awards_award_id'), table_name='contract_awards')
    op.drop_table('contract_awards')
    # ### end Alembic commands ###
