"""Trade signal models."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from news_trade.models.surprise import SignalStrength


class SignalDirection(StrEnum):
    LONG = "long"
    SHORT = "short"
    CLOSE = "close"


class DebateRound(BaseModel):
    """A single round of the bull/bear debate."""

    model_config = ConfigDict(frozen=True)

    round_number: int
    bull_argument: str
    bear_argument: str


class DebateVerdict(StrEnum):
    CONFIRM = "CONFIRM"
    REDUCE = "REDUCE"
    REJECT = "REJECT"


class DebateResult(BaseModel):
    """Outcome of the bull/bear debate for a signal."""

    model_config = ConfigDict(frozen=True)

    verdict: DebateVerdict
    confidence_delta: float = Field(
        default=0.0,
        description="Signed adjustment applied to confidence_score after debate",
    )
    rounds: list[DebateRound] = Field(default_factory=list)


class TradeSignal(BaseModel):
    """A proposed trade generated by the SignalGeneratorAgent.

    Combines sentiment analysis with market context into a concrete,
    actionable recommendation that the RiskManagerAgent will validate.
    """

    signal_id: str = Field(description="Unique signal identifier")
    event_id: str = Field(description="Originating NewsEvent id")
    ticker: str
    direction: SignalDirection
    conviction: float = Field(
        ge=0.0,
        le=1.0,
        description="Strength of the signal (0 = weak, 1 = strong)",
    )
    suggested_qty: int = Field(ge=0, description="Suggested number of shares")
    entry_price: float | None = Field(
        default=None, description="Limit price; None means market order"
    )
    stop_loss: float | None = Field(default=None)
    take_profit: float | None = Field(default=None)
    rationale: str = Field(default="")
    model_id: str = Field(default="", description="Model that produced this signal")
    provider: str = Field(default="", description="LLM provider for this signal")

    # Pattern C — confidence scoring fields
    signal_strength: SignalStrength | None = Field(
        default=None,
        description="STRONG / MODERATE / WEAK / NONE from EarningsSurprise",
    )
    confidence_score: Annotated[float, Field(ge=0.0, le=1.0)] | None = Field(
        default=None,
        description="Composite confidence score from ConfidenceScorer (0.0-1.0)",
    )
    passed_confidence_gate: bool = Field(
        default=False,
        description="True only after ConfidenceScorer.apply_gate() passes",
    )
    rejection_reason: str | None = Field(
        default=None,
        description="Human-readable reason if passed_confidence_gate is False",
    )

    # Pattern A — debate result
    debate_result: DebateResult | None = Field(
        default=None,
        description="Bull/bear debate outcome; None if debate was skipped",
    )

    created_at: datetime = Field(default_factory=datetime.utcnow)
