"""Trade signal models."""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class SignalDirection(StrEnum):
    LONG = "long"
    SHORT = "short"
    CLOSE = "close"


class TradeSignal(BaseModel):
    """A proposed trade generated by the SignalGeneratorAgent.

    Combines sentiment analysis with market context into a concrete,
    actionable recommendation that the RiskManagerAgent will validate.
    """

    signal_id: str = Field(description="Unique signal identifier")
    event_id: str = Field(description="Originating NewsEvent id")
    ticker: str
    direction: SignalDirection
    conviction: float = Field(
        ge=0.0,
        le=1.0,
        description="Strength of the signal (0 = weak, 1 = strong)",
    )
    suggested_qty: int = Field(ge=0, description="Suggested number of shares")
    entry_price: float | None = Field(
        default=None, description="Limit price; None means market order"
    )
    stop_loss: float | None = Field(default=None)
    take_profit: float | None = Field(default=None)
    rationale: str = Field(default="")
    model_id: str = Field(default="", description="Model that produced this signal")
    provider: str = Field(default="", description="LLM provider for this signal")
    created_at: datetime = Field(default_factory=datetime.utcnow)
